anchor_apply/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('overseer.urls')),
]

overseer/urls.py
from django.conf.urls import url

from . import views

app_name = 'overseer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^process/$', views.process, name='process'),
    url(r'^(?P<avaliation_id>[0-9]+)/result/$', views.result, name='result'),
]

overseer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
import re

# Create your models here.
class Avaliation(models.Model):
    upload = models.FileField(upload_to='uploads', null=False)
    result = models.TextField(null=True)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.upload.name

    def process(self):
        data = []
        result = ""
        first_line = ""
        pattern = re.compile("(^[4-6]\d{15})$|(^[4-6]\d{3}-\d{4}-\d{4}-\d{4})")
        pattern2 = re.compile(r'(.)\1{3}')
        lines = self.upload.read().splitlines()

        for line in lines:
            if len(line) > 0:
                data.append(line)

        try:
            first_line = int(data[0])
        except Exception as e:
             self.result = 'The N (first line) value must be a number'
             return self.result

        if first_line != (len(data) -1):
            self.result = 'The N (first line) value diverges from the card numbers found'
            return self.result

        data.remove(data[0])

        if len(data) > 0:
            if first_line > 0 and first_line < 100:
                for line in data:
                    if pattern.match(line):
                        if "-" in line:
                            no_hifen_line = line.replace("-","")
                            if pattern2.search(no_hifen_line):
                                result += line + ' [Invalid] \n'
                            else:
                                result += line + ' [Valid] \n'
                        else:
                            if pattern2.search(line):
                                result += line + ' [Invalid] \n'
                            else:
                                result += line + ' [Valid] \n'
                    else:
                        result += line + ' [Invalid] \n'
            else:
                result = 'N can\'t be greater than 100'
        else:
            result = 'The file can\'t be blank'

        self.result = result

        return result

overseer/forms.py
from django.forms import ModelForm
from .models import Avaliation

class AvaliationForm(ModelForm):
    class Meta:
        model = Avaliation
        fields = ['upload']

overseer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .forms import AvaliationForm
from .models import Avaliation

# Create your views here.
def index(request):
    return render(request, 'overseer/index.html')

def process(request):
    if request.method == 'POST':
        if request.FILES:
            form = AvaliationForm(request.POST, request.FILES)
            if form.is_valid():
                avaliation = Avaliation(upload=request.FILES['upload'])
                avaliation.process()
                avaliation.save()
                return HttpResponseRedirect(reverse('overseer:result', args=(avaliation.id,)))
        else:
            return HttpResponseRedirect(reverse('overseer:index'))

def result(request, avaliation_id):
    avaliation = get_object_or_404(Avaliation, pk=avaliation_id)
    return render(request, 'overseer/result.html', {'avaliation': avaliation})

overseer/templates/overseer/index.html
{% load staticfiles %}
<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/overseer.css' %}">
</head>
<div class="container">
  <div class="page-header">
    <h1>Welcome to Overseer</h1>
    <h4>Please submit the credit card file to my avaliation</h3>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <form action="{% url 'overseer:process' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputFile">File input</label>
          <input type="file" id="id_upload" name="upload">
        </div>
        <button type="submit" class="btn btn-info">
          <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Process file
        </button>
      </form>
    </div>
  </div>

</div>

overseer/templates/overseer/result.html
{% load staticfiles %}
<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/overseer.css' %}">
</head>
<div class="container">
  <div class="page-header">
    <h1>File processed!</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-tittle">Result:</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        {% for line in avaliation.result.splitlines %}
        <li class="list-group-item">{{ line }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <button type="button" class="btn btn-info pull-right" onclick="window.location.href='{% url 'overseer:index' %}'">
    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Go Back
  </button>
</div>